baseURL = "/"
title = "Rocky Linux 8.3 Documentation"
copyright = "© 2020 The Rocky Linux Foundation. All rights reserved."
languageCode = "en-us"

[params]
shortTitle = "Rocky Linux Docs"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = false
    style = "monokai"
    tabWidth = 4
